# create role that can be used to grant users permission to create smcp and smmr resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Release.Name }}-maistra-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["maistra.io"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Release.Name }}-maistra-admin
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{.Release.Name }}-maistra-admin

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Release.Name }}-istio-operator
rules:
  # operator-sdk rules
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - services/finalizers
    verbs:
      - '*'

  # operator rules for managing istio
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - namespaces
      - persistentvolumeclaims
      - pods
      - replicationcontrollers
      - secrets
      - serviceaccounts
      - services
      - events # is this needed?
    verbs:
      - '*'
  - apiGroups:
      - apps
      - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/finalizers
      - ingresses # is this needed? should it be converted to a route?
      - ingresses/status
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - '*'
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - certmanager.k8s.io
    resources:
      - clusterissuers
    verbs:
      - '*'
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
      - ingresses
    verbs:
      - '*'
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs:
      - '*'
  - apiGroups:
      - authentication.istio.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - config.istio.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - networking.istio.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - rbac.istio.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - security.istio.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - jaegertracing.io
    resources:
      - jaegers
    verbs:
      - '*'
  - apiGroups:
      - kiali.io
    resources:
      - kialis
    verbs:
      - '*'
  - apiGroups:
      - maistra.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - authentication.maistra.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - rbac.maistra.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - '*'
  # required by smmr controller
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - network.openshift.io
    resources:
      - clusternetworks
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.openshift.io
    resources:
      - networks
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - network.openshift.io
    resources:
      - netnamespaces
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - k8s.cni.cncf.io
    resources:
      - network-attachment-definitions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch

  # required by cni daemonset
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
    verbs:
      - use

  # required by pod locality controller
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
    verbs:
      - get
      - list
      - watch
  - apiGroups: # might be required by citadel
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - nonResourceURLs:
      - /metrics
    verbs:
      - get

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Release.Name }}-istio-operator-account-istio-operator-cluster-role-binding
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{.Release.Name }}-istio-operator
roleRef:
  kind: ClusterRole
  name: {{.Release.Name }}-istio-operator
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name }}-istio-operator
  namespace: {{ .Release.Namespace }}

---

apiVersion: v1
kind: Service
metadata:
  name: maistra-admission-controller
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: maistra-operator-serving-cert
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 11999
  selector:
    name: istio-operator
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-operator
  template:
    metadata:
      labels:
        name: istio-operator
      annotations:
        olm.relatedImage.v1_0.3scale-istio-adapter: quay.io/3scale/3scale-istio-adapter:v1.0.0
        olm.relatedImage.v1_0.citadel: docker.io/maistra/citadel-ubi8:1.0.8
        olm.relatedImage.v1_0.cni: docker.io/maistra/istio-cni-ubi8:1.0.8
        olm.relatedImage.v1_0.galley: docker.io/maistra/galley-ubi8:1.0.8
        olm.relatedImage.v1_0.grafana: docker.io/maistra/grafana-ubi8:1.0.8
        olm.relatedImage.v1_0.mixer: docker.io/maistra/mixer-ubi8:1.0.8
        olm.relatedImage.v1_0.pilot: docker.io/maistra/pilot-ubi8:1.0.8
        olm.relatedImage.v1_0.prometheus: docker.io/maistra/prometheus-ubi8:1.0.8
        olm.relatedImage.v1_0.proxy-init: docker.io/maistra/proxy-init-centos7:1.0.8
        olm.relatedImage.v1_0.proxyv2: docker.io/maistra/proxyv2-ubi8:1.0.8
        olm.relatedImage.v1_0.sidecar-injector: docker.io/maistra/sidecar-injector-ubi8:1.0.8

        olm.relatedImage.v1_1.3scale-istio-adapter: quay.io/3scale/3scale-istio-adapter:v1.0.0
        olm.relatedImage.v1_1.citadel: docker.io/maistra/citadel-ubi8:1.1.12
        olm.relatedImage.v1_1.cni: docker.io/maistra/istio-cni-ubi8:1.1.12
        olm.relatedImage.v1_1.galley: docker.io/maistra/galley-ubi8:1.1.12
        olm.relatedImage.v1_1.grafana: docker.io/maistra/grafana-ubi8:1.1.12
        olm.relatedImage.v1_1.ior: docker.io/maistra/istio-ior-ubi8:1.1.12
        olm.relatedImage.v1_1.mixer: docker.io/maistra/mixer-ubi8:1.1.12
        olm.relatedImage.v1_1.pilot: docker.io/maistra/pilot-ubi8:1.1.12
        olm.relatedImage.v1_1.prometheus: docker.io/maistra/prometheus-ubi8:1.1.12
        olm.relatedImage.v1_1.proxy-init: docker.io/maistra/proxy-init-centos7:1.1.12
        olm.relatedImage.v1_1.proxyv2: docker.io/maistra/proxyv2-ubi8:1.1.12
        olm.relatedImage.v1_1.sidecar-injector: docker.io/maistra/sidecar-injector-ubi8:1.1.12

        olm.relatedImage.v2_0.3scale-istio-adapter: quay.io/3scale/3scale-istio-adapter:v2.0.0
        olm.relatedImage.v2_0.cni: docker.io/maistra/istio-cni-ubi8:2.0.2
        olm.relatedImage.v2_0.grafana: docker.io/maistra/grafana-ubi8:2.0.2
        olm.relatedImage.v2_0.mixer: docker.io/maistra/mixer-ubi8:2.0.2
        olm.relatedImage.v2_0.pilot: docker.io/maistra/pilot-ubi8:2.0.2
        olm.relatedImage.v2_0.prometheus: docker.io/maistra/prometheus-ubi8:2.0.2
        olm.relatedImage.v2_0.proxy-init: docker.io/maistra/proxy-init-centos7:2.0.2
        olm.relatedImage.v2_0.proxyv2: docker.io/maistra/proxyv2-ubi8:2.0.2
        olm.relatedImage.v2_0.wasm-cacher: docker.io/maistra/pilot-ubi8:2.0.2

        olm.relatedImage.v2_1.3scale-istio-adapter: {{ .Values.images.version2_1.threeScale.repository }}:{{ .Values.images.version2_1.threeScale.tag}}
        olm.relatedImage.v2_1.cni: {{ .Values.images.version2_1.cni.repository }}:{{ .Values.images.version2_1.cni.tag}}
        olm.relatedImage.v2_1.grafana: {{ .Values.images.version2_1.grafana.repository }}:{{ .Values.images.version2_1.grafana.tag}}
        olm.relatedImage.v2_1.pilot: {{ .Values.images.version2_1.pilot.repository }}:{{ .Values.images.version2_1.pilot.tag}}
        olm.relatedImage.v2_1.prometheus: {{ .Values.images.version2_1.prometheus.repository }}:{{ .Values.images.version2_1.prometheus.tag}}
        olm.relatedImage.v2_1.proxyv2: {{ .Values.images.version2_1.proxyv2.repository }}:{{ .Values.images.version2_1.proxyv2.tag}}
        olm.relatedImage.v2_1.wasm-cacher: {{ .Values.images.version2_1.wasmCacher.repository }}:{{ .Values.images.version2_1.wasmCacher.tag}}
        olm.relatedImage.v2_1.rls: {{ .Values.images.version2_1.rls.repository }}:{{ .Values.images.version2_1.rls.tag}}

    spec:
      serviceAccountName: {{.Release.Name }}-istio-operator
      containers:
        - name: istio-operator
          image: {{ .Values.images.version2_1.operator.repository }}:{{ .Values.images.version2_1.operator.tag}}
          ports:
            - containerPort: 11999
              name: validation
            - containerPort: 60000
              name: metrics
          command:
            - istio-operator
            - --config
            - /etc/operator/olm/config.properties
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: istio-operator
          #        - name: ISTIO_CNI_IMAGE_PULL_SECRET
          #          value: name-of-secret
          volumeMounts:
            - name: operator-olm-config
              mountPath: /etc/operator/olm
              readOnly: true
            - name: webhook-tls-volume
              readOnly: true
              mountPath: /tmp/k8s-webhook-server/serving-certs
            - name: smcp-templates
              readOnly: true
              mountPath: /usr/local/share/istio-operator/templates/
            - name: custom-global-yaml
              readOnly: true
              mountPath: /usr/local/share/istio-operator/helm/v2.1/global.yaml
              subPath: global.yaml
      volumes:
        - name: operator-olm-config
          downwardAPI:
            defaultMode: 420
            items:
              - fieldRef:
                  fieldPath: metadata.annotations
                path: config.properties
        - name: webhook-tls-volume
          secret:
            secretName: maistra-operator-serving-cert
            optional: true # this won't be available until service-ca creates the secret
        - name: smcp-templates
          configMap:
            name: smcp-templates
            optional: true
        - name: custom-global-yaml
          configMap:
            name: {{ .Release.Name }}-configmap
            optional: true